# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e01400ad236518bf7987197561c4aea3aa14927ff59916b849ead23a0a746b36a4b34837df9b9a801d9b2a3d0dca73113c6e6dd22ded8cb0fd76456a2014912

test:
  secret_key_base: d67815c3476c519ce7adc8daf17c042c2cf0a4efe18055b7325ae36fb3cc248aaa71e691063619c1689faffde3e69d65cfbd94d7ab2b9714b9d713436c854747

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
